version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql_container:3306/mydb
      DB_USER: arun
      DB_PASS: user
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest                  # Use official MySQL 8 image
    container_name: mysql_container     # Name of the container                   # Automatically restart if it stops
    environment:
        MYSQL_DATABASE: mydb
        MYSQL_USER: arun
        MYSQL_ROOT_PASSWORD: user    # Password for new user
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge